### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by Fsunroo** [TomPrograms/Simple-Python-File-Transfer-Server#1]
when I run the server.py on the cellphone and client.py on laptop, I get `ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it`

and when I run server.py on laptop and client.py on cellphone, I get `TimeoutError: [Errno 110] Connection timed out`

***there is no antivir on laptop and windows defender is deactive

*** I have not installed any kind of network security software on my cellphone neither (but I'm not sure whether there is any kind of preinstalled application)

**Comment by TomPrograms** [comment]
The `ConnectionRefusedError` occurs when you try and connect to a machine that doesn't have the server running already. Maybe the address is wrong. Also a firewall might be causing the issue.

I'm not sure what is causing the `TimeOut` error. Maybe the server/client is dropping off the connection which is causing the issue. Sorry I couldn't be more specific. I believe these are probably issues with your setup not the code.

**Comment by ahnorr** [comment]
@Fsunroo  if you Change the bind value from IP to an empty string your issue should be solved. 
From : 
    `self.s.bind((ip,port))`
To : 
     `self.s.bind(("",port))`
